version: '3.1'
services:
  mongo:
    #build: . # Instead of build you can use 'image: mongo'
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_DATABASE: coinwatch
    volumes:
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-data:/data/db

  tsdb:
    build:
      context: .
      dockerfile: "tsdb.dockerfile"
    image: coinwatch-tsdb
    environment:
      POSTGRES_PASSWORD: pass123
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - tsdb-data:/home/postgres/pgdata/data


  coinwatch-server:
    build:
      context: .
      dockerfile: "coinwatch.dockerfile"
    image: coinwatch
    depends_on:
      - mongo
      - tsdb
    environment:
      COIN_WATCH_ENV: docker
    ports:
      - "4243:4243"
    command: ["python", "/app/coinmarket/coin_market.py"]

  coinwatch-dashboard:
    image: coinwatch
    depends_on:
      - coinwatch-server
    environment:
      COIN_WATCH_ENV: docker
    ports:
      - "8051:8051"
    command: ["streamlit", "run", "/app/coinmarket/dashboard.py", "--server.port=8051", "--server.address=0.0.0.0"]


volumes:
  mongo-data:
  tsdb-data:

